name: RecNet Prod-Release Pipeline

on:
  workflow_dispatch: {}
  push:
    # branches:
    #   - dev

jobs:
  release:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RecNet Release Action
        uses: ./libs/recnet-release-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head-branch: test-release-action
          base-branch: master
          repo: ${{ github.repository }}
          ref: 4573543f2f5a3abf9e7f81140cdb33a8175271e2

  # update-tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update staging tag
  #       uses: actions/github-script@v5
  #       with:
  #         script: |
  #           github.rest.git.updateRef({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             ref: 'refs/tags/staging',
  #             sha: context.sha
  #           })
