name: RecNet Release Action

on:
  workflow_dispatch: {}
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run RecNet Release Action
        uses: ./libs/recnet-release-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          head-branch: dev
          base-branch: master
          repo: ${{ github.repository }}
          ref: f4d0d9874091417844fff836a87be666d7df99f5
